FROM openjdk:11 as builder

WORKDIR /spring

# perform layer caching of dependencies
COPY gradle/ ./gradle/
COPY gradlew ./
COPY build.gradle ./
COPY settings.gradle ./
RUN ./gradlew --no-daemon dependencies

# build the JAR artifact
COPY classes.lst ./
COPY src/ src/
RUN ./gradlew --no-daemon build

FROM gcr.io/distroless/java:11

COPY --from=amd64/busybox:1.31.1 /bin/busybox /busybox/busybox
RUN ["/busybox/busybox", "--install", "/bin"]

WORKDIR /spring

EXPOSE 8080 9090

ENTRYPOINT ["java", "-server", "-Xshare:on", "-XX:SharedArchiveFile=spring-boot.jsa", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=50.0", "-XX:ThreadStackSize=256", "-XX:MaxMetaspaceSize=128m", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=250", "-XX:+UseStringDeduplication", "-Djava.security.egd=file:/dev/./urandom", "-Dcom.sun.management.jmxremote", "-Dcom.sun.management.jmxremote.port=9090", "-Djava.rmi.server.hostname=localhost", "-Dcom.sun.management.jmxremote.rmi.port=9090", "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.authenticate=false", "-jar", "spring-boot-appcds.jar"]

ENV APPCDS_ENABLED=true

COPY --from=builder /spring/build/libs/spring-boot-appcds.jar ./
COPY --from=builder /spring/build/classes.lst ./

RUN java -Xshare:dump -XX:SharedClassListFile=classes.lst -XX:SharedArchiveFile=spring-boot.jsa -jar spring-boot-appcds.jar && \
    rm -rf classes.lst